Fix parsing width/height for audio attachments
mastodon/mastodon-ios pull request #611
Opened 2022-11-16 22:43 UTC by j-f1

Fixes #414. It seems like Mastodon no longer serves width/height on the `original` key in some/all cases. So I’m pulling the only available size (from `small`) instead.

2022-11-18 19:29 UTC, tejuamirthi approved these changes

2022-12-26 18:00 UTC, zeitschlag requested changes

2022-12-26 18:00 UTC, zeitschlag commented on MastodonSDK/Sources/MastodonCore/Extension/CoreDataStack/Status+Property.swift
> +            }
This doesn't really help, if `meta.small` is nil.

```
(lldb) po media.remoteURL
▿ Optional<String>
  - some : "https://cdn.masto.host/mastodonart/media_attachments/files/109/302/787/076/266/355/original/04519903aafd999c.mp3"

(lldb) po meta
▿ Meta
  ▿ original : Optional<Format>
    ▿ some : Format
      - width : nil
      - height : nil
      - size : nil
      - aspect : nil
      - frameRate : nil
      ▿ duration : Optional<Double>
        - some : 205.688163
      ▿ bitrate : Optional<Int>
        - some : 162203
  - small : nil
  ▿ focus : Optional<Focus>
    ▿ some : Focus
      - x : 0.0
      - y : 0.0
  - length : nil
  - duration : nil
  - fps : nil
  - size : nil
  - width : nil
  - height : nil
  - aspect : nil
  - audioEncode : nil
  - audioBitrate : nil
  - audioChannels : nil
```

It's this [toot](https://mastodon.art/@simonstalenhag/109302790092203385) from the issue.

2022-12-26 18:02 UTC, j-f1 commented
Agreed, I think https://github.com/mastodon/mastodon-ios/pull/805 is the better solution here. Closing.

2022-12-26 18:02 UTC, closed without merging